apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: nehacodessampleaspcoreapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nehacodessampleaspcoreapp 
    spec:
      containers:
        - name: nehacodessampleaspcoreapp 
          image: reviewapp.azurecr.io/nehacodessampleaspcoreapp
          ports:
          - containerPort: 80